# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(max_length=200, verbose_name='简介')),
                ('content', models.TextField(help_text='A content for this thing', verbose_name='正文')),
                ('create_date', models.DateField(default=datetime.datetime.now)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(max_length=200, verbose_name='简介')),
                ('content', models.TextField(help_text='A content for this thing', verbose_name='正文')),
                ('banner_type', models.CharField(choices=[('BANNER_LEFT', 'bnr_lft'), ('BANNER_RIGHT_GRID1', 'bnr_rht_grid1'), ('BANNER_RIGHT_GRID2', 'bnr_rht_grid2'), ('BANNER_RIGHT_GRID3', 'bnr_rht_grid3'), ('BANNER_RIGHT_GRID4', 'bnr_rht_grid4'), ('NONE', 'none')], default='NONE', max_length=200, verbose_name='是否图片栏')),
                ('background_image', models.ImageField(blank=True, storage=editor.models.OverwriteStorage(), upload_to='img')),
            ],
        ),
    ]
