# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(help_text='A content for this thing', null=True, verbose_name='正文'),
        ),
    ]
