# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20160826_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='editor_generated',
            field=models.BooleanField(default=False),
        ),
    ]
