# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_candidate_offer_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='offer_path',
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
